### ISSUE TITLE
Windows 用バイナリ配布のリンクの表示が崩れている？

### ISSUE THREAD

**Issue by machakann** [vim-jp/vim-jp.github.com#162]
すいません、もしかするとこちらの環境要因かもしれませんが vim-jp のページの Windows 用バイナリ配布リンクの部分の表示が崩れて見えています。よろしければご確認をお願いいたします。
![vim-jp_ss](https://cloud.githubusercontent.com/assets/480049/8762111/c5f011fa-2da1-11e5-9889-4b0a090f7b35.png)

**Comment by koron** [comment]
さーせんわたしのせいです。なおします。

**Comment by koron** [comment]
https://github.com/vim-jp/vim-jp.github.com/commit/690feeeb9f5304e3eed9d0797c1ac7c2c69a2453#diff-69cb2c60ade563f7533c5f5bac421be4L1 ＜このへんを消しちゃったのが原因。

**Comment by koron** [comment]
@machakann 報告、ありがとうございました :bow:

**Comment by machakann** [comment]
ありがとうございました！

**Comment by lesguillemets** [comment]
（バージョンも巻き戻ってしまって更新されていないような…！）

**Comment by machakann** [comment]
7.4.788 のバイナリがダウンロードできますけど、HPの表示は 7.4.763 になっていました。

**Comment by k-takata** [comment]
直しました。

**Comment by machakann** [comment]
確認しました、ありがとうございます。

**Comment by lesguillemets** [comment]
ありがとうございました．
