### ISSUE TITLE
jekyll 3.x への備え

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.com#175]
github-pages はまだ jekyll 2.4 だけど、いつ3.xに移行する日がわからんので、準備だけは進めておきましょう。

とりあえず [prepare-jekyll-3.x ブランチ](https://github.com/vim-jp/vim-jp.github.com/tree/prepare-jekyll-3.x) で、今やっても問題のない最低限のところだけ、やっておきました。

**Comment by ynkdir** [comment]
GitHub Pages now faster and simpler with Jekyll 3.0 
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by koron** [comment]
やったぜ。準備しておいて、良かった…

**Comment by koron** [comment]
と思ったら、以下の点はさらに作業が必要。
一部はすぐにではなさそうなので issue は分けたほうが良いかも。

* kramdownが唯一のサポートされたmarkdown engine になる from 1st May 2016
* ハイライターがrouge (pure ruby)に切り替わる
  * `{% highlight %}` タグは使えなくなる
* 相対パーマリンクはサポートされない
* textileのサポート中止 at 1st May 2016

**Comment by koron** [comment]
merged #179 . completed.

**Comment by koron** [comment]
これに伴うかもしれない問題を発見したら、別途issue立ててください。
