### ISSUE TITLE
Patchesが表示されていない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vim-jp.github.com#183]
トップページの Patches の欄が空になってしまっています。

あと、別件かもしれませんがtwitterのvim_jpで、説明が長すぎてパッチへのリンクが入っていないことがあります。
https://twitter.com/vim_jp/status/703994862052491266

**Comment by k-takata** [comment]
ついでに、リンクが間違っています。
https://twitter.com/vim_jp/status/702631747037609985

**Comment by mattn** [comment]
ほんとですか？

![](http://go-gyazo.appspot.com/d4e6cd4b695769f6.png)

**Comment by k-takata** [comment]
Oh, 今見たら出ていますね。

**Comment by k-takata** [comment]
> * Patch 7.4.1459  
>   Patch 7.4.1459 Problem ...

パッチ番号が2回表示されているのは冗長ですねぇ。

**Comment by mattn** [comment]
URLはコミットIDが入ったおかげで長くなったんですね。。。

**Comment by mattn** [comment]
直しました。

https://github.com/vim-jp/post_issues/commit/c2046d1683031e985fa2e7279fc8a26c224223b4

問題あれば再度 open って事で close

**Comment by mattn** [comment]
冗長の件があった。

**Comment by mattn** [comment]
fixed https://github.com/vim-jp/vim-jp.github.com/commit/24196a7a0a72e4bc932c717f37781bd4da5735b0

**Comment by k-takata** [comment]
thx!
